/*
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package com.ericsson.toside.ui.tests;

import cbbdemo.ui.internal.CbbdemoActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class CBBdemoUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CbbdemoActivator.getInstance().getInjector("com.ericsson.toside.CBBdemo");
	}

}
