/*
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package com.ericsson.toside.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class CBBdemoUiModule extends AbstractCBBdemoUiModule {
}
