/*
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package com.ericsson.toside


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CBBdemoStandaloneSetup extends CBBdemoStandaloneSetupGenerated {

	def static void doSetup() {
		new CBBdemoStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
