/*
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package com.ericsson.toside.ide.contentassist.antlr;

import com.ericsson.toside.ide.contentassist.antlr.internal.InternalCBBdemoParser;
import com.ericsson.toside.services.CBBdemoGrammarAccess;
import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class CBBdemoParser extends AbstractContentAssistParser {

	@Inject
	private CBBdemoGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalCBBdemoParser createParser() {
		InternalCBBdemoParser result = new InternalCBBdemoParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getStatementAccess().getAlternatives(), "rule__Statement__Alternatives");
					put(grammarAccess.getGreetingAccess().getGroup(), "rule__Greeting__Group__0");
					put(grammarAccess.getGoodbyeAccess().getGroup(), "rule__Goodbye__Group__0");
					put(grammarAccess.getProgramAccess().getStatementsAssignment(), "rule__Program__StatementsAssignment");
					put(grammarAccess.getGreetingAccess().getNameAssignment_1(), "rule__Greeting__NameAssignment_1");
					put(grammarAccess.getGoodbyeAccess().getNameAssignment_1(), "rule__Goodbye__NameAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public CBBdemoGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CBBdemoGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
