/**
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package com.ericsson.toside.cbbdemo.impl;

import com.ericsson.toside.cbbdemo.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class CbbdemoFactoryImpl extends EFactoryImpl implements CbbdemoFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static CbbdemoFactory init()
  {
    try
    {
      CbbdemoFactory theCbbdemoFactory = (CbbdemoFactory)EPackage.Registry.INSTANCE.getEFactory(CbbdemoPackage.eNS_URI);
      if (theCbbdemoFactory != null)
      {
        return theCbbdemoFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new CbbdemoFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CbbdemoFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case CbbdemoPackage.PROGRAM: return createProgram();
      case CbbdemoPackage.STATEMENT: return createStatement();
      case CbbdemoPackage.GREETING: return createGreeting();
      case CbbdemoPackage.GOODBYE: return createGoodbye();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Program createProgram()
  {
    ProgramImpl program = new ProgramImpl();
    return program;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Statement createStatement()
  {
    StatementImpl statement = new StatementImpl();
    return statement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Greeting createGreeting()
  {
    GreetingImpl greeting = new GreetingImpl();
    return greeting;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Goodbye createGoodbye()
  {
    GoodbyeImpl goodbye = new GoodbyeImpl();
    return goodbye;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CbbdemoPackage getCbbdemoPackage()
  {
    return (CbbdemoPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static CbbdemoPackage getPackage()
  {
    return CbbdemoPackage.eINSTANCE;
  }

} //CbbdemoFactoryImpl
