/**
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package com.ericsson.toside.cbbdemo.impl;

import com.ericsson.toside.cbbdemo.CbbdemoPackage;
import com.ericsson.toside.cbbdemo.Goodbye;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Goodbye</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class GoodbyeImpl extends StatementImpl implements Goodbye
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GoodbyeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CbbdemoPackage.Literals.GOODBYE;
  }

} //GoodbyeImpl
