/**
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package com.ericsson.toside.cbbdemo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Goodbye</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.ericsson.toside.cbbdemo.CbbdemoPackage#getGoodbye()
 * @model
 * @generated
 */
public interface Goodbye extends Statement
{
} // Goodbye
