/*
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package com.ericsson.toside.parser.antlr;

import com.ericsson.toside.parser.antlr.internal.InternalCBBdemoParser;
import com.ericsson.toside.services.CBBdemoGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class CBBdemoParser extends AbstractAntlrParser {

	@Inject
	private CBBdemoGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCBBdemoParser createParser(XtextTokenStream stream) {
		return new InternalCBBdemoParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public CBBdemoGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CBBdemoGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
