/*
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package com.ericsson.toside.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CBBdemoAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/ericsson/toside/parser/antlr/internal/InternalCBBdemo.tokens");
	}
}
