/*
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package com.ericsson.toside.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCBBdemoScopeProvider extends DelegatingScopeProvider {
}
