/*
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package com.ericsson.toside.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractCBBdemoValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(com.ericsson.toside.cbbdemo.CbbdemoPackage.eINSTANCE);
		return result;
	}
	
}
