/*
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package com.ericsson.toside.ui.outline

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
class CBBdemoOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
